### ISSUE TITLE
Unable to install via brew

### ISSUE THREAD

**Issue by JoshHrach** [simonbs/dependency-graph#8]
### What happened?

Attempting to install via `brew` reveals the following error:

> error: 'dependency-graph-20221212-22643-1xg8p9v': Invalid manifest
/private/tmp/dependency-graph-20221212-22643-1xg8p9v/Package.swift:4:8: error: no such module 'PackageDescription'

> Do not report this issue to Homebrew/brew or Homebrew/core!

> /opt/homebrew/Library/Homebrew/utils/github/api.rb:306:in `raise_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::API::ValidationFailedError)

### What are the steps to reproduce?

1. Follow install instructions in readme for tapping
2. Try `brew install dependency-graph`

### What is the expected behavior?

`brew` would properly install `dependency-graph`.

**Comment by simonbs** [comment]
From the error message it seems the `swift build` is unable to find the PackageDescription module when building dependency-graph.

What does the following command output?

```bash
xcode-select --print-path
```

It may be pointing at a wrong path, eg. a beta version of Xcode that is no longer installed on the system or the CLI tools. In that case it should be reverted to point to Xcode with the following command.

```bash
xcode-select --switch /your/path/to/Xcode
```

**Comment by JoshHrach** [comment]
My output for --print-path:
> /Library/Developer/CommandLineTools

Switching to point to Xcode fixed it. Thank you!
